# Generated by Django 4.2.6 on 2023-10-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.ManyToManyField(related_name='name_title', to='apps.title'),
        ),
    ]
