# Generated by Django 4.2.6 on 2023-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='title',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
