# Generated by Django 4.2.6 on 2023-10-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_title_name_title_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_subtitle', to='apps.title')),
            ],
            options={
                'verbose_name': 'Подзаголовок',
                'verbose_name_plural': 'Подзаголовки',
            },
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
