# Generated by Django 4.2.6 on 2023-12-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_title_name_alter_title_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовки'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='url',
        ),
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='title',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_name', to='apps.title'),
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_name', to='apps.title')),
            ],
            options={
                'verbose_name': 'Подзаголовок',
                'verbose_name_plural': 'Подзаголовки',
            },
        ),
    ]
