# Generated by Django 4.2.6 on 2023-10-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_title_name_subtitle_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='parent_subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_subtitle', to='apps.subtitle'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='parent_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_subtitle', to='apps.title'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
