# Generated by Django 4.2.6 on 2023-10-23 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_subtitle_parent_subtitle_subtitle_parent_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_name', to='apps.title'),
        ),
        migrations.DeleteModel(
            name='SubTitle',
        ),
    ]
