# Generated by Django 4.2.6 on 2023-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_title_parent_delete_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Headers'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='parent',
        ),
        migrations.AddField(
            model_name='title',
            name='url',
            field=models.CharField(default=1, max_length=255, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
