# Generated by Django 4.2.6 on 2023-11-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_title_options_remove_title_parent_title_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='url',
        ),
    ]
